### ISSUE TITLE
How to reproduce the CRS of test 2?

### ISSUE THREAD

**Issue by xiaowu759** [shane5ul/pyReSpect-time#2]
I used the default setting in inp.dat to test the test 2 in the tests directory. I found that the DRS could be reproduced successfully. But the CRS (say H.dat) exhibits only bimodal not four modes as expected. How to reproduce the CRS in Figure 2b in the paper [Macromol. Theory Simul. 2019, 1900005]? Could you give me some hints, please?

H.dat: 
2.078796e-04 -5.785635e+00
2.410452e-04 -5.642137e+00
2.795021e-04 -5.498639e+00
3.240945e-04 -5.355141e+00
3.758014e-04 -5.211644e+00
4.357576e-04 -5.068146e+00
5.052794e-04 -4.924649e+00
5.858929e-04 -4.781154e+00
6.793676e-04 -4.637662e+00
7.877556e-04 -4.494175e+00
9.134360e-04 -4.350699e+00
1.059168e-03 -4.207240e+00
1.228150e-03 -4.063808e+00
1.424092e-03 -3.920420e+00
1.651295e-03 -3.777099e+00
1.914746e-03 -3.633878e+00
2.220230e-03 -3.490805e+00
2.574450e-03 -3.347942e+00
2.985184e-03 -3.205373e+00
3.461448e-03 -3.063208e+00
4.013695e-03 -2.921591e+00
4.654050e-03 -2.780698e+00
5.396568e-03 -2.640755e+00
6.257550e-03 -2.502032e+00
7.255894e-03 -2.364857e+00
8.413517e-03 -2.229617e+00
9.755829e-03 -2.096761e+00
1.131230e-02 -1.966798e+00
1.311709e-02 -1.840299e+00
1.520982e-02 -1.717885e+00
1.763643e-02 -1.600220e+00
2.045019e-02 -1.487988e+00
2.371286e-02 -1.381879e+00
2.749607e-02 -1.282554e+00
3.188286e-02 -1.190621e+00
3.696952e-02 -1.106600e+00
4.286773e-02 -1.030895e+00
4.970695e-02 -9.637634e-01
5.763732e-02 -9.052949e-01
6.683291e-02 -8.554025e-01
7.749559e-02 -8.138203e-01
8.985943e-02 -7.801143e-01
1.041958e-01 -7.537056e-01
1.208195e-01 -7.339024e-01
1.400953e-01 -7.199385e-01
1.624464e-01 -7.110155e-01
1.883635e-01 -7.063446e-01
2.184155e-01 -7.051847e-01
2.532620e-01 -7.068740e-01
2.936680e-01 -7.108541e-01
3.405205e-01 -7.166850e-01
3.948480e-01 -7.240518e-01
4.578430e-01 -7.327624e-01
5.308884e-01 -7.427391e-01
6.155876e-01 -7.540035e-01
7.137999e-01 -7.666547e-01
8.276812e-01 -7.808445e-01
9.597314e-01 -7.967449e-01
1.112849e+00 -8.145124e-01
1.290396e+00 -8.342457e-01
1.496269e+00 -8.559398e-01
1.734987e+00 -8.794369e-01
2.011791e+00 -9.043774e-01
2.332757e+00 -9.301558e-01
2.704931e+00 -9.558872e-01
3.136482e+00 -9.803907e-01
3.636884e+00 -1.002197e+00
4.217121e+00 -1.019589e+00
4.889930e+00 -1.030674e+00
5.670081e+00 -1.033499e+00
6.574700e+00 -1.026205e+00
7.623643e+00 -1.007219e+00
8.839937e+00 -9.754756e-01
1.025028e+01 -9.306622e-01
1.188564e+01 -8.734646e-01
1.378190e+01 -8.057913e-01
1.598070e+01 -7.309370e-01
1.853029e+01 -6.536395e-01
2.148666e+01 -5.799788e-01
2.491470e+01 -5.170739e-01
2.888965e+01 -4.725616e-01
3.349877e+01 -4.538915e-01
3.884324e+01 -4.675359e-01
4.504039e+01 -5.182642e-01
5.222624e+01 -6.086473e-01
6.055853e+01 -7.389039e-01
7.022019e+01 -9.071082e-01
8.142328e+01 -1.109675e+00
9.441375e+01 -1.341978e+00
1.094767e+02 -1.598965e+00
1.269429e+02 -1.875654e+00
1.471957e+02 -2.167486e+00
1.706797e+02 -2.470512e+00
1.979103e+02 -2.781477e+00
2.294854e+02 -3.097803e+00
2.660980e+02 -3.417531e+00
3.085519e+02 -3.739242e+00
3.577791e+02 -4.061963e+00
4.148600e+02 -4.385089e+00
4.810477e+02 -4.708303e+00

**Comment by shane5ul** [comment]
The easiest way here is to pick a lower lambda. You can do this, for
example, by setting:

lamC : 0
SmFacLam : -0.8

I modified (improved, I hope) the CRS algorithm after the paper was
published to better approximate experimental spectra. I now use a Bayesian
formulation to determine the critical lambda since the old method (L-curve)
used in the paper often resulted in too small lambda. While that was a good
choice for artificial tests such as test2, it created squiggles for more
realistic data (see test6, and discussion in the paper). With the new
method for critical lambda, the program produces a smooth CRS for test6.

I hope this helps.

**Comment by xiaowu759** [comment]
It really works. Thank you very much!
