### ISSUE TITLE
an imcomplete CRS

### ISSUE THREAD

**Issue by xiaowu759** [shane5ul/pyReSpect-time#3]
I have generated the H(t) from P2.dat using the pyReSpect-time tool with the default settings. As one consequence, the H(t) appears to be imcomplete, namely, the peak at the longer time does not show at all. The data in the two files are attached below. How to deal with this problem? Thank you for any reply!

P2.dat:
5	0.7325
10	0.66744
15	0.62167
20	0.58591
25	0.55637
30	0.53125
35	0.50954
40	0.49054
45	0.47351
50	0.45811
55	0.44451
60	0.43189
65	0.42033
70	0.40968
75	0.39989
80	0.39088
85	0.38256
90	0.37476
95	0.3673
100	0.36052
105	0.35395
110	0.34783
115	0.34206
120	0.33652
125	0.33139
130	0.32648
135	0.32183
140	0.31741
145	0.31318
150	0.30926
155	0.30542
160	0.30173
165	0.29822
170	0.29477
175	0.29162
180	0.28853
185	0.28553
190	0.2827
195	0.27986
200	0.27709
205	0.27453
210	0.27221
215	0.26981
220	0.26757
225	0.26538
230	0.2632
235	0.26112
240	0.25896
245	0.25692
250	0.25501
255	0.25315
260	0.25135
265	0.24953
270	0.24783
275	0.24623
280	0.24468
285	0.24312
290	0.24151
295	0.2399
300	0.23848
305	0.23699
310	0.23563
315	0.23421
320	0.23286
325	0.23159
330	0.23038
335	0.2291
340	0.22786
345	0.22664
350	0.22554
355	0.2244
360	0.22337
365	0.22224
370	0.2211
375	0.21992
380	0.21885
385	0.2179
390	0.21688
395	0.21584
400	0.21487
405	0.21398
410	0.213
415	0.21203
420	0.21119
425	0.21034
430	0.20939
435	0.20845
440	0.20759
445	0.20673
450	0.20591
455	0.20515
460	0.20427
465	0.20354
470	0.20272
475	0.20188
480	0.2011
485	0.2003
490	0.19959
495	0.19878
500	0.198
505	0.19734
510	0.1968
515	0.19623
520	0.19537
525	0.19471
530	0.19411
535	0.19346
540	0.19276
545	0.19212
550	0.19152
555	0.19089
560	0.19037
565	0.18986
570	0.18927
575	0.18875
580	0.18824
585	0.18762
590	0.18707
595	0.18659
600	0.18604
605	0.18545
610	0.18494
615	0.18434
620	0.18389
625	0.1834
630	0.18281
635	0.18232
640	0.18168
645	0.18114
650	0.18061
655	0.18007
660	0.17953
665	0.17919
670	0.17862
675	0.17822
680	0.17774
685	0.17734
690	0.17682
695	0.1763
700	0.17577
705	0.1753
710	0.17471
715	0.17418
720	0.17373
725	0.1733
730	0.17283
735	0.17253
740	0.172
745	0.1716
750	0.17113
755	0.17064
760	0.1702
765	0.16985
770	0.16948
775	0.16914
780	0.1688
785	0.16836
790	0.16792
795	0.16751
800	0.1672
805	0.16683
810	0.16658
815	0.16617
820	0.16575
825	0.16539
830	0.165
835	0.16461
840	0.16423
845	0.16384
850	0.16346
855	0.16301
860	0.16277
865	0.16242
870	0.16212
875	0.16178
880	0.16137
885	0.16109
890	0.16078
895	0.16045
900	0.16007
905	0.1598
910	0.15946
915	0.15911
920	0.15886
925	0.15854
930	0.15817
935	0.1581
940	0.15774
945	0.15745
950	0.1571
955	0.15666
960	0.15641
965	0.15617
970	0.15579
975	0.15551
980	0.15522
985	0.15492
990	0.15475
995	0.15461
1000	0.15439
1005	0.15417
1010	0.15387
1015	0.15366
1020	0.15329
1025	0.15296
1030	0.15276
1035	0.15239
1040	0.15218
1045	0.15184
1050	0.15152
1055	0.15128
1060	0.15102
1065	0.15076
1070	0.15053
1075	0.15037
1080	0.15001
1085	0.14975
1090	0.14962
1095	0.14932
1100	0.14905
1105	0.14874
1110	0.14851
1115	0.14815
1120	0.14786
1125	0.14757
1130	0.14727
1135	0.1471
1140	0.14699
1145	0.14673
1150	0.14653
1155	0.14625
1160	0.14598
1165	0.14587
1170	0.14547
1175	0.14527
1180	0.14504
1185	0.14483
1190	0.14457
1195	0.1444
1200	0.14425
1205	0.1441
1210	0.14385
1215	0.14364
1220	0.14351
1225	0.14325
1230	0.14307
1235	0.14274
1240	0.14249
1245	0.14219
1250	0.14197
1255	0.1417
1260	0.1415
1265	0.14118
1270	0.1409
1275	0.14063
1280	0.14025
1285	0.13994
1290	0.13975
1295	0.13946
1300	0.13916
1305	0.13885
1310	0.13865
1315	0.13845
1320	0.13818
1325	0.13783
1330	0.13762
1335	0.13748
1340	0.13733
1345	0.13712
1350	0.1369
1355	0.13669
1360	0.13653
1365	0.13632
1370	0.13612
1375	0.13594
1380	0.13573
1385	0.13548
1390	0.1353
1395	0.13513
1400	0.13491
1405	0.13478
1410	0.13454
1415	0.13439
1420	0.13422
1425	0.13408
1430	0.13388
1435	0.13373
1440	0.13351
1445	0.13329
1450	0.13304
1455	0.13283
1460	0.1327
1465	0.13263
1470	0.13239
1475	0.13213
1480	0.13192
1485	0.1318
1490	0.13157
1495	0.13128
1500	0.13116
1505	0.13102
1510	0.13095
1515	0.13079
1520	0.13068
1525	0.13051
1530	0.13025
1535	0.13007
1540	0.12998
1545	0.12974
1550	0.1296
1555	0.12935
1560	0.12925
1565	0.129
1570	0.12881
1575	0.12858
1580	0.12846
1585	0.12832
1590	0.12818
1595	0.12796
1600	0.1277
1605	0.12766
1610	0.12742
1615	0.12727
1620	0.12714
1625	0.12695
1630	0.12684
1635	0.12676
1640	0.1267
1645	0.12648
1650	0.12635
1655	0.12624
1660	0.12614
1665	0.12601
1670	0.12589
1675	0.12574
1680	0.12548
1685	0.12546
1690	0.12533
1695	0.12517
1700	0.12503
1705	0.12489
1710	0.12474
1715	0.12453
1720	0.12439
1725	0.12415
1730	0.1239
1735	0.12368
1740	0.12348
1745	0.12327
1750	0.12304
1755	0.12294
1760	0.12275
1765	0.12268
1770	0.12262
1775	0.12244
1780	0.1223
1785	0.12218
1790	0.12208
1795	0.12179
1800	0.12159
1805	0.12147
1810	0.12127
1815	0.12118
1820	0.12105
1825	0.12089
1830	0.12063
1835	0.12048
1840	0.12029
1845	0.12014
1850	0.12004
1855	0.11992
1860	0.11975
1865	0.11949
1870	0.11939
1875	0.11917
1880	0.11903
1885	0.11891
1890	0.11886
1895	0.11867
1900	0.11852
1905	0.11843
1910	0.11812
1915	0.11801
1920	0.11795
1925	0.11783
1930	0.1177
1935	0.11766
1940	0.11745
1945	0.11718
1950	0.11695
1955	0.11675
1960	0.11665
1965	0.11655
1970	0.11635
1975	0.11619
1980	0.11596
1985	0.11592
1990	0.11576
1995	0.11575
2000	0.11569
2005	0.1157
2010	0.11549
2015	0.11544
2020	0.11524
2025	0.11503
2030	0.11504
2035	0.11506
2040	0.11496
2045	0.11488
2050	0.11481
2055	0.11468
2060	0.11459
2065	0.11445
2070	0.11432
2075	0.11415
2080	0.11392
2085	0.11374
2090	0.11352
2095	0.1134
2100	0.11326
2105	0.11322
2110	0.11312
2115	0.11299
2120	0.11298
2125	0.11294
2130	0.11283
2135	0.11277
2140	0.11263
2145	0.11251
2150	0.11235
2155	0.11233
2160	0.11227
2165	0.11199
2170	0.11176
2175	0.11159
2180	0.11142
2185	0.11137
2190	0.11133
2195	0.11126
2200	0.11125
2205	0.11123
2210	0.11117
2215	0.11108
2220	0.11101
2225	0.11086
2230	0.11076
2235	0.11068
2240	0.1106
2245	0.11038
2250	0.11031
2255	0.11024
2260	0.11015
2265	0.11005
2270	0.10996
2275	0.10985
2280	0.10985
2285	0.10973
2290	0.10961
2295	0.10954
2300	0.10929
2305	0.1092
2310	0.10915
2315	0.10887
2320	0.10875
2325	0.1085
2330	0.10838
2335	0.10826
2340	0.10818
2345	0.108
2350	0.10795
2355	0.10784
2360	0.10772
2365	0.10744
2370	0.10738
2375	0.10731
2380	0.10712
2385	0.107
2390	0.10691
2395	0.10676
2400	0.10661
2405	0.10643
2410	0.10634
2415	0.10626
2420	0.10627
2425	0.10618
2430	0.10595
2435	0.10595
2440	0.10601
2445	0.10587
2450	0.10569
2455	0.10558
2460	0.10551
2465	0.1054
2470	0.10531
2475	0.10523
2480	0.10511
2485	0.10501
2490	0.10501
2495	0.10501
2500	0.10486
2505	0.10469
2510	0.10469
2515	0.10464
2520	0.10461
2525	0.10447
2530	0.10433
2535	0.1043
2540	0.1043
2545	0.1041
2550	0.10399
2555	0.10391
2560	0.10386
2565	0.10381
2570	0.10374
2575	0.10355
2580	0.10337
2585	0.10335
2590	0.10315
2595	0.10308
2600	0.10284
2605	0.10272
2610	0.10252
2615	0.10247
2620	0.10235
2625	0.10231
2630	0.10223
2635	0.10207
2640	0.10201
2645	0.10186
2650	0.10183
2655	0.10161
2660	0.10151
2665	0.1014
2670	0.10138
2675	0.10132
2680	0.10111
2685	0.10103
2690	0.10102
2695	0.10093
2700	0.10084
2705	0.10077
2710	0.10069
2715	0.10048
2720	0.1005
2725	0.10047
2730	0.10038
2735	0.10028
2740	0.10006
2745	0.09995

H.dat:
1.039398e+00 -4.078540e+00
1.143499e+00 -4.012017e+00
1.258027e+00 -3.945495e+00
1.384025e+00 -3.878973e+00
1.522642e+00 -3.812451e+00
1.675143e+00 -3.745930e+00
1.842918e+00 -3.679410e+00
2.027496e+00 -3.612892e+00
2.230561e+00 -3.546376e+00
2.453963e+00 -3.479862e+00
2.699741e+00 -3.413353e+00
2.970135e+00 -3.346848e+00
3.267610e+00 -3.280348e+00
3.594878e+00 -3.213852e+00
3.954925e+00 -3.147362e+00
4.351032e+00 -3.080875e+00
4.786811e+00 -3.014392e+00
5.266236e+00 -2.947914e+00
5.793678e+00 -2.881444e+00
6.373945e+00 -2.814986e+00
7.012330e+00 -2.748554e+00
7.714653e+00 -2.682166e+00
8.487317e+00 -2.615855e+00
9.337368e+00 -2.549670e+00
1.027256e+01 -2.483679e+00
1.130141e+01 -2.417979e+00
1.243330e+01 -2.352698e+00
1.367857e+01 -2.288002e+00
1.504855e+01 -2.224102e+00
1.655574e+01 -2.161259e+00
1.821389e+01 -2.099784e+00
2.003811e+01 -2.040047e+00
2.204503e+01 -1.982468e+00
2.425296e+01 -1.927523e+00
2.668202e+01 -1.875731e+00
2.935437e+01 -1.827645e+00
3.229437e+01 -1.783840e+00
3.552882e+01 -1.744897e+00
3.908723e+01 -1.711377e+00
4.300202e+01 -1.683806e+00
4.730891e+01 -1.662644e+00
5.204715e+01 -1.648273e+00
5.725995e+01 -1.640968e+00
6.299484e+01 -1.640888e+00
6.930412e+01 -1.648063e+00
7.624530e+01 -1.662393e+00
8.388167e+01 -1.683650e+00
9.228287e+01 -1.711490e+00
1.015255e+02 -1.745466e+00
1.116938e+02 -1.785051e+00
1.228806e+02 -1.829660e+00
1.351877e+02 -1.878672e+00
1.487275e+02 -1.931453e+00
1.636233e+02 -1.987375e+00
1.800111e+02 -2.045834e+00
1.980402e+02 -2.106258e+00
2.178750e+02 -2.168116e+00
2.396963e+02 -2.230920e+00
2.637032e+02 -2.294222e+00
2.901145e+02 -2.357610e+00
3.191710e+02 -2.420700e+00
3.511377e+02 -2.483130e+00
3.863061e+02 -2.544548e+00
4.249967e+02 -2.604605e+00
4.675624e+02 -2.662950e+00
5.143913e+02 -2.719226e+00
5.659103e+02 -2.773064e+00
6.225893e+02 -2.824087e+00
6.849450e+02 -2.871909e+00
7.535459e+02 -2.916143e+00
8.290176e+02 -2.956401e+00
9.120481e+02 -2.992306e+00
1.003395e+03 -3.023495e+00
1.103890e+03 -3.049628e+00
1.214451e+03 -3.070392e+00
1.336084e+03 -3.085513e+00
1.469900e+03 -3.094756e+00
1.617119e+03 -3.097932e+00
1.779082e+03 -3.094903e+00
1.957267e+03 -3.085584e+00
2.153297e+03 -3.069946e+00
2.368962e+03 -3.048014e+00
2.606226e+03 -3.019874e+00
2.867253e+03 -2.985664e+00
3.154424e+03 -2.945581e+00
3.470357e+03 -2.899874e+00
3.817932e+03 -2.848840e+00
4.200318e+03 -2.792827e+00
4.621003e+03 -2.732220e+00
5.083821e+03 -2.667443e+00
5.592993e+03 -2.598949e+00
6.153161e+03 -2.527211e+00
6.769434e+03 -2.452717e+00
7.447429e+03 -2.375955e+00
8.193329e+03 -2.297405e+00
9.013935e+03 -2.217523e+00
9.916729e+03 -2.136727e+00
1.090994e+04 -2.055378e+00
1.200263e+04 -1.973765e+00
1.320476e+04 -1.892080e+00

**Comment by shane5ul** [comment]
Strictly speaking the range of H inference cannot be greater than the range
of the data (t = 5-2745) in your data. Since pyReSpect uses the lenient
setting (FreqEnd : 1) by default, the CRS actually goes beyond the actual
range of the data (1-13,205).

If you try to use FreqEnd : 2 so that the range of the CRS matches that of
the data, then you'll notice that your fit (Gfit) is not great, unless you
also set the "plateau" flag to "True". This is because when slower modes
that are not explicitly captured in the data are present, their signature
in G(t) is indistinguishable  long-time plateau.

I believe this is the correct behavior and posture for pyReSpect.

If you want to play with the range of the CRS manually, then you can modify
the treatment of the "FreqEnd" flag in contSpec.py (at your own risk). Set
smin and smax in the following piece of code.

 # determine frequency window
if par['FreqEnd'] == 1:
smin = np.exp(-np.pi/2) * tmin; smax = np.exp(np.pi/2) * tmax

**Comment by xiaowu759** [comment]
Your reply is quite helpful. Thank you very much!

**Comment by shane5ul** [comment]
Thanks for all the feedback! I really appreciate your interest.
